name: serverpod_ts_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  analyzer: ^7.5.6
  interact: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
